// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nothing.Model.Data;

namespace Nothing.Model.Migrations
{
    [DbContext(typeof(NothingDBContext))]
    [Migration("20200321065612_sometable")]
    partial class sometable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Nothing.Model.Entity.Language", b =>
                {
                    b.Property<int>("ID_Language")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Key_Language")
                        .IsRequired()
                        .HasColumnType("varchar(99)");

                    b.Property<string>("Language_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language_VN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Language");

                    b.ToTable("Language");
                });

            modelBuilder.Entity("Nothing.Model.Entity.MenuAdmin", b =>
                {
                    b.Property<int>("Id_Menu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NameMenu")
                        .IsRequired()
                        .HasColumnType("varchar(99)");

                    b.Property<int>("ParentID")
                        .HasColumnType("int");

                    b.Property<string>("Where")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Menu");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("Nothing.Model.Entity.Profile", b =>
                {
                    b.Property<int>("Id_Profile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Displayname")
                        .IsRequired()
                        .HasColumnType("varchar(99)");

                    b.Property<string>("DoctorComment")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<int>("Id_User")
                        .HasColumnType("int");

                    b.Property<string>("Pathological")
                        .IsRequired()
                        .HasColumnType("varchar(999)");

                    b.HasKey("Id_Profile");

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("Nothing.Model.Entity.Role", b =>
                {
                    b.Property<int>("Id_Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Role_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id_Role");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Nothing.Model.Entity.User", b =>
                {
                    b.Property<int>("Id_User")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Id_Role")
                        .HasColumnType("int");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("varchar(99)");

                    b.Property<string>("RoleMenu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(99)");

                    b.HasKey("Id_User");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
